name: Iain Phillips
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo


